// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAIssuer) DeepCopyInto(out *AWSPCAIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAIssuer.
func (in *AWSPCAIssuer) DeepCopy() *AWSPCAIssuer {
	if in == nil {
		return nil
	}
	out := new(AWSPCAIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPCAIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAIssuerCondition) DeepCopyInto(out *AWSPCAIssuerCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAIssuerCondition.
func (in *AWSPCAIssuerCondition) DeepCopy() *AWSPCAIssuerCondition {
	if in == nil {
		return nil
	}
	out := new(AWSPCAIssuerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAIssuerList) DeepCopyInto(out *AWSPCAIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSPCAIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAIssuerList.
func (in *AWSPCAIssuerList) DeepCopy() *AWSPCAIssuerList {
	if in == nil {
		return nil
	}
	out := new(AWSPCAIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSPCAIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAIssuerSpec) DeepCopyInto(out *AWSPCAIssuerSpec) {
	*out = *in
	out.Provisioner = in.Provisioner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAIssuerSpec.
func (in *AWSPCAIssuerSpec) DeepCopy() *AWSPCAIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(AWSPCAIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAIssuerStatus) DeepCopyInto(out *AWSPCAIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AWSPCAIssuerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAIssuerStatus.
func (in *AWSPCAIssuerStatus) DeepCopy() *AWSPCAIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(AWSPCAIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSPCAProvisioner) DeepCopyInto(out *AWSPCAProvisioner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSPCAProvisioner.
func (in *AWSPCAProvisioner) DeepCopy() *AWSPCAProvisioner {
	if in == nil {
		return nil
	}
	out := new(AWSPCAProvisioner)
	in.DeepCopyInto(out)
	return out
}
